CevdetAkiah/chess-website

.github/workflows/docker-image.yml
This doesn't push the images anywhere or anything like that, but we now are able to ensure that the containers build :)
=> Add github action for building containers

deploy/dev/backend/configmap.yaml
reset the yaml file to what it was originally as I'd accidentally pushed a modified version to main. This was causing an error on deployment.
=> configmap.yaml reset

client/src/components/userform/login-form/index.jsx
form no longer freezes if email is entered incorrectly
=> email verification fixed 

server/mux/mux.go, server/route/route_get.go
healthz handler to allow kubernetes to health check the pod
=> healthz handler

client/src/components/healthcheck/index.jsx, client/src/components/router/index.jsx
frontend path for kubernetes to check /healthz
=> healthz for the frontend

deploy/dev/backend/configmap.yaml
PORT 8080 added to configmap.yaml
=> PORT added to configmap.yaml

server/mux/mux.go
Adding BACKEND_HOST to allowed origins
=> updating cors

server/route/route_get.go
adding the header to allow chess.dev.adamland.xyz as origin
=> NewUserAuthentication handler header

client/src/functions/authentication.js, server/cmd/main.go, server/mux/mux.go, server/route/route_get.go, server/route/route_post.go
added PORT and adamland as env variables
=> configuring env variables

client/src/functions/authentication.js
added chess-backend as endpoint for authUser route
=> testing authUser

client/src/functions/authentication.js, server/database/postgres/session_table.go, server/mux/mux.go, server/route/route_get.go, server/route/route_post.go, server/route/util.go, server/service/session.go, server/service/user.go
added timeout code to handlers which will detect if a session has gone over the time limit without user input, and if user has input then the session is updated with a new time limit.
If timeout then user is logged out.
=> timeout session

client/src/pages/Game/index.jsx
added checkSession to the Game so each time an action is performed by either player the session is updated server side to stop time outs
=> game session pulse

client/src/pages/Game/index.jsx
written to allow checkSession and checkGameID to run before the websocket launches. On websocket close; if the websocket wasn't closed properly it will re initialize
=> asynchronous initializeWebsocket function

client/src/functions/authentication.js, client/src/pages/Game/index.jsx, server/chesswebsocket/chesswebsocket.go, server/route/route_get.go
NewGameIDAuthorizer returns "new-game" as the gameID element if there is no current game cookie. initializeWebSocket no longer awaits checkSession and checkGameID
=> websocket disconnect fix

client/src/pages/Game/index.jsx, server/chesswebsocket/chesswebsocket.go
handleReconnect function added to the WsGame struct in chesswebsocket. First step on handling player reconnect through re renders of the game.
=> step one on handling player reconnect 

client/src/pages/Game/index.jsx, server/chesswebsocket/chesswebsocket.go, server/chesswebsocket/models.go
Up to date fen and player info is being sent to the client on re render (reconnect). However, once reconnected it's no longer possible to continue playing. Need to fix in the next PR.
=> part 2 of game persistence

client/src/pages/Game/index.jsx, server/chesswebsocket/chesswebsocket.go
Added some more logic to the reconnect function on the client side to ensure the board is rebuilt on reconnect.
Reconnect information also sent to the opponent on the server side.
I believe this is as far as I can go with game persistence using localhost as a testing ground.
=> game persistence

server/chesswebsocket/chesswebsocket.go
Mutex locking/unlocking when shared resources are accessed within chesswebsocket. Aiming to stop potential race conditions.
=> Chesswebsocket concurrent-safety

server/cmd/main.go, server/mux/mux.go, server/route/route_delete.go, server/route/route_get.go, server/route/route_post.go, server/route/route_post_test.go, server/route/route_put.go, server/route/util.go, server/service/database_access.go, server/util/helpers.go
refactored the http handlers so they return early and are easier to read
=> handler early return refactor

server/cmd/main.go, server/config/config.go, server/database/postgres/models.go
This pull request introduces configuration structs to organize environment variables related to the database connection and server settings. The changes aim to enhance readability, maintainability, and flexibility in managing configuration options.
Changes made:
=> configuration structs

server/route/route_post.go, server/route/route_test.go
Test implemented for NewLoginHandler
=> route tests

server/route/route_test.go
Test for NewDeleteUser implemented. 
Test creates a test user, cookie  and session, then checks for:
User delete from the DB
Session delete from the DB
=> route tests delete

server/route/route_test.go
Test implemented for the NewLogoutUser function. 
Test creates a test user and session for the user, inserting the session into the db, then checks if the session has been removed from the DB after using NewLogoutUser.
=> Route delete tests

server/route/route_test.go
Test implemented for the NewUpdateUser function.
Test creates a test user and adds to the DB.
The user details are then changed and updated using NewUpdateUser.
User state is then checked on the DB to ensure user details have updated.
=> route put tests

server/mux/mux.go
healthz is failing in Kubernetes. Testing if it's how the mux is handling the endpoint that is the causing the probem.
=> test healthz

client/src/components/userform/login-form/index.jsx, server/cmd/main.go, server/config/config.go, server/mux/mux.go, server/route/route_delete.go, server/route/route_get.go, server/route/route_post.go, server/route/route_put.go
context withtimeout added to remaining handlers and mux configured
=> context.WithTimeout added to handlers and config files to mux

client/src/components/userform/login-form/index.jsx, client/src/components/userform/register-form/index.jsx, client/src/functions/authentication.js
timeout errors dealt with in the client
=> timeout errors

.github/workflows/ci.yml
Change: remove the docker env variables from the ci.yml (github actions workflow).
The env variables will be passed to the kubernetes environment in the future
=> remove docker env variables

.github/workflows/ci.yml
the purpose is to apply the kubernetes manifests to my cluster and create the secret pgapp
=> update to gitactions

.github/workflows/ci.yml, deploy/dev/postgres/postgres.yaml
updating the postgres owner from chess to admin
=> owner: admin

.github/workflows/ci.yml, deploy/dev/backend/kustomization.yaml
testing other CI for now as the yaml to create the secret in actions wasn't working and blocking the rest of the flow
=> deleted secret create in ci.yml

deploy/dev/backend/deployment.yaml, deploy/dev/backend/kustomization.yaml, deploy/dev/kustomization.yaml, deploy/dev/namespaces/kustomization.yaml, deploy/dev/namespaces/postgres-dev.yaml, deploy/dev/postgres/kustomization.yaml
changed postgres to chess-dev namespace and pointed chess-dev backend deployment to the chess-dev-app secret
=> postgres to chess-dev namespace
